#!/usr/bin/env bash
#        _
# __   _| |__   _____  __
# \ \ / / '_ \ / _ \ \/ /
#  \ V /| |_) | (_) >  <
#   \_/ |_.__/ \___/_/\_\
#
# A streamlined interface for VBoxManage, the VirtualBox command line tool.
#
# Depends on:
#  VBoxManage, part of VirtualBox
#
# Bash Boilerplate: https://github.com/alphabetum/bash-boilerplate
#
# Copyright (c) 2016 William Melody • hi@williammelody.com

###############################################################################
# Strict Mode
###############################################################################

set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

###############################################################################
# Globals
###############################################################################

# $_VERSION
#
# Manually set this to to current version of the program. Adhere to the
# semantic versioning specification: http://semver.org
_VERSION="1.0.2"

# $DEFAULT_COMMAND
#
# The command to be run by default, when no command name is specified. If the
# environment has an existing $DEFAULT_COMMAND set, then that value is used.
DEFAULT_COMMAND="${DEFAULT_COMMAND:-help}"

###############################################################################
# Debug
###############################################################################

# _debug()
#
# Usage:
#   _debug printf "Debug info. Variable: %s\n" "$0"
#
# A simple function for executing a specified command if the `$_USE_DEBUG`
# variable has been set. The command is expected to print a message and
# should typically be either `echo`, `printf`, or `cat`.
__DEBUG_COUNTER=0
_debug() {
  if [[ "${_USE_DEBUG:-"0"}" -eq 1 ]]
  then
    __DEBUG_COUNTER=$((__DEBUG_COUNTER+1))
    # Prefix debug message with "bug (U+1F41B)"
    printf "🐛  %s " "${__DEBUG_COUNTER}"
    "$@"
    printf "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――\n"
  fi
}
# debug()
#
# Usage:
#   debug "Debug info. Variable: $0"
#
# Print the specified message if the `$_USE_DEBUG` variable has been set.
#
# This is a shortcut for the _debug() function that simply echos the message.
debug() {
  _debug echo "$@"
}

###############################################################################
# Die
###############################################################################

# _die()
#
# Usage:
#   _die printf "Error message. Variable: %s\n" "$0"
#
# A simple function for exiting with an error after executing the specified
# command. The command is expected to print a message and should typically
# be either `echo`, `printf`, or `cat`.
_die() {
  # Prefix die message with "cross mark (U+274C)", often displayed as a red x.
  printf "❌  "
  "$@" 1>&2
  exit 1
}
# die()
#
# Usage:
#   die "Error message. Variable: $0"
#
# Exit with an error and print the specified message.
#
# This is a shortcut for the _die() function that simply echos the message.
die() {
  _die echo "$@"
}

###############################################################################
# Options
###############################################################################

# Get raw options for any commands that expect them.
_RAW_OPTIONS="$*"

# Steps:
#
# 1. set expected short options in `optstring` at beginning of the "Normalize
#    Options" section,
# 2. parse options in while loop in the "Parse Options" section.

# Normalize Options ###########################################################

# Source:
#   https://github.com/e36freak/templates/blob/master/options

# The first loop, even though it uses 'optstring', will NOT check if an
# option that takes a required argument has the argument provided. That must
# be done within the second loop and case statement, yourself. Its purpose
# is solely to determine that -oARG is split into -o ARG, and not -o -A -R -G.

# Set short options -----------------------------------------------------------

# option string, for short options.
#
# Very much like getopts, expected short options should be appended to the
# string here. Any option followed by a ':' takes a required argument.
#
# In this example, `-x` and `-h` are regular short options, while `o` is
# assumed to have an argument and will be split if joined with the string,
# meaning `-oARG` would be split to `-o ARG`.
optstring=h

# Normalize -------------------------------------------------------------------

# iterate over options, breaking -ab into -a -b and --foo=bar into --foo bar
# also turns -- into --endopts to avoid issues with things like '-o-', the '-'
# should not indicate the end of options, but be an invalid option (or the
# argument to the option, such as wget -qO-)
unset options
# while the number of arguments is greater than 0
while (($#))
do
  case $1 in
    # if option is of type -ab
    -[!-]?*)
      # loop over each character starting with the second
      for ((i=1; i<${#1}; i++))
      do
        # extract 1 character from position 'i'
        c=${1:i:1}
        # add current char to options
        options+=("-$c")

        # if option takes a required argument, and it's not the last char
        # make the rest of the string its argument
        if [[ $optstring = *"$c:"* && ${1:i+1} ]]
        then
          options+=("${1:i+1}")
          break
        fi
      done
      ;;
    # if option is of type --foo=bar, split on first '='
    --?*=*)
      options+=("${1%%=*}" "${1#*=}")
      ;;
    # end of options, stop breaking them up
    --)
      options+=(--endopts)
      shift
      options+=("$@")
      break
      ;;
    # otherwise, nothing special
    *)
      options+=("$1")
      ;;
  esac

  shift
done
# set new positional parameters to altered options. Set default to blank.
set -- "${options[@]:-}"
unset options

# Parse Options ###############################################################

# Initialize $_COMMAND_ARGV array
#
# This array contains all of the arguments that get passed along to each
# command. This is essentially the same as the program arguments, minus those
# that have been filtered out in the program option parsing loop. This array
# is initialized with $0, which is the program's name.
_COMMAND_ARGV=("$0")
# Initialize $_CMD and `$_USE_DEBUG`, which can continue to be blank depending
# on what the program needs.
_CMD=""
_USE_DEBUG=0

while [ $# -gt 0 ]
do
  opt="$1"
  shift
  case "$opt" in
    -h|--help)
      _CMD="help"
      ;;
    --version)
      _CMD="version"
      ;;
    --debug)
      _USE_DEBUG=1
      ;;
    *)
      # The first non-option argument is assumed to be the command name.
      # All subsequent arguments are added to $_COMMAND_ARGV.
      if [[ -n $_CMD ]]
      then
        _COMMAND_ARGV+=("$opt")
      else
        _CMD="$opt"
      fi
      ;;
  esac
done

# Set $_COMMAND_PARAMETERS to $_COMMAND_ARGV, minus the initial element, $0. This
# provides an array that is equivalent to $* and $@ within each command
# function, though the array is zero-indexed, which could lead to confusion.
#
# Use `unset` to remove the first element rather than slicing (e.g.,
# `_COMMAND_PARAMETERS=("${_COMMAND_ARGV[@]:1}")`) because under bash 3.2 the
# resulting slice is treated as a quoted string and doesn't easily get coaxed
# into a new array.
_COMMAND_PARAMETERS=(${_COMMAND_ARGV[*]})
unset _COMMAND_PARAMETERS[0]

_debug printf "\$_CMD: %s\n" "$_CMD"
_debug printf "\$_RAW_OPTIONS (one per line):\n%s\n" "$_RAW_OPTIONS"
_debug printf "\$_COMMAND_ARGV: %s\n" "${_COMMAND_ARGV[*]}"
_debug printf "\$_COMMAND_PARAMETERS: %s\n" "${_COMMAND_PARAMETERS[*]:-}"

###############################################################################
# Environment
###############################################################################

# $_ME
#
# Set to the program's basename.
_ME=$(basename "$0")

_debug printf "\$_ME: %s\n" "$_ME"

###############################################################################
# Load Commands
###############################################################################

# Initialize $_DEFINED_COMMANDS array.
_DEFINED_COMMANDS=()

# _load_commands()
#
# Usage:
#   _load_commands
#
# Loads all of the commands sourced in the environment.
_load_commands() {

  _debug printf "_load_commands(): entering...\n"
  _debug printf "_load_commands() declare -F:\n%s\n" "$(declare -F)"

  # declare is a bash built-in shell function that, when called with the '-F'
  # option, displays all of the functions with the format
  # `declare -f function_name`. These are then assigned as elements in the
  # $function_list array.
  local function_list=($(declare -F))

  for c in "${function_list[@]}"
  do
    # Each element has the format `declare -f function_name`, so set the name
    # to only the 'function_name' part of the string.
    local function_name
    function_name=$(printf "%s" "$c" | awk '{ print $3 }')

    _debug printf "_load_commands() \$function_name: %s\n" "$function_name"

    # Add the function name to the $_DEFINED_COMMANDS array unless it starts
    # with an underscore or is one of the desc(), debug(), or die() functions,
    # since these are treated as having 'private' visibility.
    if ! ( [[ "$function_name" =~ ^_(.*)  ]] || \
           [[ "$function_name" == "desc"  ]] || \
           [[ "$function_name" == "debug" ]] || \
           [[ "$function_name" == "die"   ]]
    )
    then
      _DEFINED_COMMANDS+=("$function_name")
    fi
  done

  _debug printf \
    "commands() \$_DEFINED_COMMANDS:\n%s\n" \
    "${_DEFINED_COMMANDS[*]:-}"
}

###############################################################################
# Main
###############################################################################

# _main()
#
# Usage:
#   _main
#
# The primary function for starting the program.
#
# NOTE: must be called at end of program after all commands have been defined.
_main() {
  _debug printf "main(): entering...\n"
  _debug printf "main() \$_CMD (upon entering): %s\n" "$_CMD"

  # If $_CMD is blank, then set to `$DEFAULT_COMMAND`
  if [[ -z $_CMD ]]
  then
    _CMD="$DEFAULT_COMMAND"
  fi

  # Load all of the commands.
  _load_commands

  # If the command is defined, run it, otherwise return an error.
  if _contains "$_CMD" "${_DEFINED_COMMANDS[*]:-}"
  then
    # Pass all comment arguments to the program except for the first ($0).
    $_CMD "${_COMMAND_PARAMETERS[@]:-}"
  else
    _die printf "Unknown command: %s\n" "$_CMD"
  fi
}

###############################################################################
# Utility Functions
###############################################################################

# _function_exists()
#
# Usage:
#   _function_exists "possible_function_name"
#
# Returns:
#   0  If a function with the given name is defined in the current environment.
#   1  If not.
#
# Other implementations, some with better performance:
# http://stackoverflow.com/q/85880
_function_exists() {
  [ "$(type -t "$1")" == 'function' ]
}

# _command_exists()
#
# Usage:
#   _command_exists "possible_command_name"
#
# Returns:
#   0  If a command with the given name is defined in the current environment.
#   1  If not.
#
# Information on why `hash` is used here:
# http://stackoverflow.com/a/677212
_command_exists() {
  hash "$1" 2>/dev/null
}

# _contains()
#
# Usage:
#   _contains "$item" "${list[*]}"
#
# Returns:
#   0  If the item is included in the list.
#   1  If not.
_contains() {
  local test_list=(${*:2})
  for _test_element in "${test_list[@]:-}"
  do
    _debug printf "_contains() \$_test_element: %s\n" "$_test_element"
    if [[ "$_test_element" == "$1" ]]
    then
      _debug printf "_contains() match: %s\n" "$1"
      return 0
    fi
  done
  return 1
}

# _join()
#
# Usage:
#   _join "," a b c
#   _join "${an_array[@]}"
#
# Returns:
#   The list or array of items joined into a string with elements divided by
#   the optional separator if one is provided.
_join() {
  local separator
  local target_array
  local dirty
  local clean
  separator="$1"
  target_array=(${@:2})
  dirty="$(printf "${separator}%s"  "${target_array[@]}")"
  clean="${dirty:${#separator}}"
  printf "%s" "${clean}"
}

# _command_argv_includes()
#
# Usage:
#   _command_argv_includes "an_argument"
#
# Returns:
#   0  If the argument is included in `$_COMMAND_ARGV`, the program's command
#      argument list.
#   1  If not.
#
# This is a shortcut for simple cases where a command wants to check for the
# presence of options quickly without parsing the options again.
_command_argv_includes() {
  _contains "$1" "${_COMMAND_ARGV[*]}"
}

# _blank()
#
# Usage:
#   _blank "$an_argument"
#
# Returns:
#   0  If the argument is not present or null.
#   1  If the argument is present and not null.
_blank() {
  [[ -z "${1:-}" ]]
}

# _present()
#
# Usage:
#   _present "$an_argument"
#
# Returns:
#   0  If the argument is present and not null.
#   1  If the argument is not present or null.
_present() {
  [[ -n "${1:-}" ]]
}

# _interactive_input()
#
# Usage:
#   _interactive_input
#
# Returns:
#   0  If the current input is interactive (eg, a shell).
#   1  If the current input is stdin / piped input.
_interactive_input() {
  [[ -t 0 ]]
}

# _piped_input()
#
# Usage:
#   _piped_input
#
# Returns:
#   0  If the current input is stdin / piped input.
#   1  If the current input is interactive (eg, a shell).
_piped_input() {
  ! _interactive_input
}

# _emojify_status()
#
# Usage:
#   _emojify_status <string>
#   echo <string> | _emojify_status
#
# Description:
#   Add emoji to status messages.
_emojify_status() {
  local _status_string="${1:-}"

  if [[ -n "${_status_string}" ]]
  then
    _status_string="${_status_string//aborted/❕ aborted}"
    _status_string="${_status_string//paused/⏸ paused}"
    _status_string="${_status_string//powered/⚫️ powered}"
    _status_string="${_status_string//running/✅ running}"
    _status_string="${_status_string//saved/💾 saved}"

    printf "%s\n" "$_status_string"
  else
    _die printf "Usage: _emojify_status <string>\n"
  fi
}

###############################################################################
# desc
###############################################################################

# desc()
#
# Usage:
#   desc command "description"
#
# Create a description for a specified command name. The command description
# text can be passed as the second argument or as standard input.
#
# To make the description text available to other functions, desc() assigns the
# text to a variable with the format $_desc_function_name
#
# NOTE:
#
# The `read` form of assignment is used for a balance of ease of
# implementation and simplicity. There is an alternative assignment form
# that could be used here:
#
# var="$(cat <<'EOM'
# some message
# EOM
# )
#
# However, this form appears to require trailing space after backslases to
# preserve newlines, which is unexpected. Using `read` simply requires
# escaping backslashes, which is more common.
desc() {
  set +e
  [[ -z $1 ]] && _die printf "desc: No command name specified.\n"
  if [[ -n ${2:-} ]]
  then
    read -d '' "_desc_$1" <<EOM
$2
EOM
    _debug printf "desc() set with argument: _desc_%s\n" "$1"
  else
    read -d '' "_desc_$1"
    _debug printf "desc() set with pipe: _desc_%s\n" "$1"
  fi
  set -e
}

# _print_desc()
#
# Usage:
#   _print_desc <command>
#
# Prints the description for a given command, provided the description has been
# set using the desc() function.
_print_desc() {
  local var="_desc_$1"
  if [[ -n ${!var:-} ]]
  then
    printf "%s\n" "${!var}"
  else
    printf "No additional information for \`%s\`\n" "$1"
  fi
}

###############################################################################
# Default Commands
###############################################################################

# Version #####################################################################

desc "version" <<EOM
Usage:
  $_ME (version | --version)

Description:
  Display the current program version.

  To save you the trouble, the current version is $_VERSION
EOM
version() {
  printf "%s\n" "$_VERSION"
}

# Help ########################################################################

desc "help" <<EOM
Usage:
  $_ME help [<command>]

Description:
  Display help information for $_ME or a specified command.
EOM
help() {
  if [[ ${#_COMMAND_ARGV[@]} = 1 ]]
  then
    cat <<EOM
       _
__   _| |__   _____  __
\ \ / / '_ \ / _ \ \/ /
 \ V /| |_) | (_) >  <
  \_/ |_.__/ \___/_/\_\\

A streamlined interface for VBoxManage, the VirtualBox command line tool.

Version: $_VERSION

Usage:
  $_ME commands [--raw]
  $_ME forwarding add <vm-name> <rule-name> <port>
  $_ME forwarding list <vm-name>
  $_ME forwarding delete <vm-name> <rule-name>
  $_ME (help [<command>] | -h | --help)
  $_ME kill   (<name> | <uuid>)
  $_ME list   [running | status]
  $_ME manage [<general option>] <command>
  $_ME pause  (<name> | <uuid>)
  $_ME reset  (<name> | <uuid>)
  $_ME resume (<name> | <uuid>)
  $_ME show   (<name> | <uuid>)
  $_ME start  (<name> | <uuid>) [--headless]
  $_ME status [(<name> | <uuid>) [--long|-l]]
  $_ME stop   (<name> | <uuid>)
  $_ME (version | --version)

Global Options:
  -h --help  Display this help information.
  --version  Display version information.

Help:
  $_ME help [<command>]

$(commands)
EOM
  else
    _print_desc "$1"
  fi
}

# Command List ################################################################

desc "commands" <<EOM
Usage:
  $_ME commands [--raw]

Options:
  --raw  Display the command list without formatting.

Description:
  Display the list of available commands.
EOM
commands() {
  if _command_argv_includes "--raw"
  then
    printf "%s\n" "${_DEFINED_COMMANDS[@]}"
  else
    printf "Available commands:\n"
    printf "  %s\n" "${_DEFINED_COMMANDS[@]}"
  fi
}

###############################################################################
# Commands
# ========.....................................................................
#
# Example command group structure:
#
# desc example ""   - Optional. A short description for the command.
# example() { : }   - The command called by the user.
#
#
# desc example <<EOM
#   Usage:
#     $_ME example
#
#   Description:
#     Print "Hello, World!"
#
#     For usage formatting conventions see:
#     - http://docopt.org/
#     - http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
# EOM
# example() {
#   printf "Hello, World!\n"
# }
#
###############################################################################

# ------------------------------------------------------------------ forwarding

desc "forwarding" <<EOM
Usage:
  $_ME forwarding add <vm-name> <rule-name> <port>
  $_ME forwarding list <vm-name>
  $_ME forwarding delete <vm-name> <rule-name>

Subcommands:
  add     Add a new port forwarding rule.
  list    List forwarding rules.
  delete  Delete the specified rule.

Description:
  Manage port forwarding.

Example:
  $_ME forwarding add "ubuntu-vm" "tcp5000" "5000"

  Equivalent of:
    VBoxManage controlvm ubuntu-vm \\\\
      natpf1 "tcp5000,tcp,127.0.0.1,5000,,5000"
EOM
# VBoxManage controlvm fields:
#
# [--natpf<1-N> [<rulename>],tcp|udp,[<hostip>],
#               <hostport>,[<guestip>],<guestport>]
forwarding() {
  local _subcommand=
  local _arguments=()

  for arg in "${_COMMAND_ARGV[@]:-}"
  do
    case "${arg}" in
      add|list|delete)
        if [[ -z "${_subcommand}" ]]
        then
          _subcommand="${arg}"
        else
          _arguments+=("${arg}")
        fi
        ;;
      *)
        _arguments+=("${arg}")
        ;;
    esac
  done

  _debug printf "forwarding() \$_subcommand: %s\n" "${_subcommand:-}"
  if [[ -z "${_subcommand}" ]]
  then
    $_ME help forwarding
    exit 1
  fi

  _vm="${_arguments[1]:-}"
  _debug printf "forwarding() \$_vm: %s\n" "${_vm}"
  if [[ -z "${_vm}" ]]
  then
    _die printf "VM name missing.\n"
  fi

  case "$_subcommand" in
    add)
      local _name="${_arguments[2]:-}"
      local _port="${_arguments[3]:-}"

      _debug printf "forwarding() \$_arguments[2]: %s\n" "${_arguments[2]:-}"
      _debug printf "forwarding() \$_arguments[3]: %s\n" "${_arguments[3]:-}"

      if [[ -z "${_name}" ]]
      then
        _die printf "Rule name missing.\n"
      fi
      if [[ -z "${_port}" ]]
      then
        _die printf "Port missing.\n"
      fi

      VBoxManage controlvm "${_vm}" \
        natpf1 "${_name},tcp,127.0.0.1,${_port},,${_port}"
      ;;
    list)
      VBoxManage showvminfo "${_vm}" | awk '/NIC/ && /Rule/ {print}'
      ;;
    delete)
      local _name="${_arguments[2]:-}"
      if [[ -z "${_name}" ]]
      then
        _die printf "Rule name missing.\n"
      fi
      VBoxManage modifyvm "${_vm}" --natpf1 delete "${_name}"
      ;;
  esac
}

# ------------------------------------------------------------------------ kill

desc "kill" <<EOM
Usage:
  $_ME kill (<name> | <uuid>)

Description:
  Command: \`VBoxManage controlvm <vm> poweroff\`

  Has the same effect on a virtual machine as pulling the power cable on a real
  computer. The state of the VM is not saved beforehand, and data may be lost.
  (This is equivalent to selecting the "Close" item in the "Machine" menu of
  the GUI or pressing the window's close button, and then selecting "Power off
  the machine" in the dialog.)
EOM
kill() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" poweroff
}

# ------------------------------------------------------------------------ list

desc "list" <<EOM
Usage:
  $_ME list [running | status]

Arguments:
  running  List all running VMs.
  status   Display all VMs with basic status information.

Description:
  List VirtualBox VMs.
EOM
list() {
  if _contains "running" "${_COMMAND_PARAMETERS[@]:-}"
  then
    VBoxManage list runningvms
  elif _contains "status" "${_COMMAND_PARAMETERS[@]:-}"
  then
    local _vm_status_list
    _vm_status_list="$(
      VBoxManage list vms -l \
        | awk '/^Name:[ ]{5,}|^State:[ ]{5,}/ {print}' \
        | sed s/\ \ //g \
        | cut -d: -f2-
    )"
    _emojify_status "$_vm_status_list"
  else
    VBoxManage list vms
  fi
}

# ---------------------------------------------------------------------- manage

desc "manage" <<EOM
Usage:
  $_ME manage [<general option>] <command>

Description:
  Alias for \`VBoxManage\`.

  VBoxManage Documentation:
    https://www.virtualbox.org/manual/ch08.html
EOM
manage() {
  if [[ -z "${_COMMAND_PARAMETERS[@]:-}" ]]
  then
    VBoxManage
  else
    VBoxManage "${_COMMAND_PARAMETERS[@]:-}"
  fi
}

# ----------------------------------------------------------------------- pause

desc "pause" <<EOM
Usage:
  $_ME pause (<name> | <uuid>)

Description:
  Command: \`VBoxManage controlvm <vm> pause\`

  Temporarily puts a virtual machine on hold, without changing its state for
  good. The VM window will be painted in gray to indicate that the VM is
  currently paused. (This is equivalent to selecting the "Pause" item in the
  "Machine" menu of the GUI.)
EOM
pause() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" pause
}

# ----------------------------------------------------------------------- reset

desc "reset" <<EOM
Usage:
  $_ME reset (<name> | <uuid>)

Description:
  Command: \`VBoxManage controlvm <vm> reset\`

  Has the same effect on a virtual machine as pressing the "Reset" button on a
  real computer: a cold reboot of the virtual machine, which will restart and
  boot the guest operating system again immediately. The state of the VM is not
  saved beforehand, and data may be lost. (This is equivalent to selecting the
  "Reset" item in the "Machine" menu of the GUI.)
EOM
reset() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" reset
}

# ---------------------------------------------------------------------- resume

desc "resume" <<EOM
Usage:
  $_ME resume (<name> | <uuid>)

Description:
  Command: \`VBoxManage controlvm <vm> resume\`

  Undo a previous pause command. (This is equivalent to selecting the "Resume"
  item in the "Machine" menu of the GUI.)
EOM
resume() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" resume
}

# ------------------------------------------------------------------------ show

desc "show" <<EOM
Usage:
  $_ME show (<name> | <uuid>)

Description:
  Command: \`VBoxManage showvminfo <vm>\`

  Show information about a particular virtual machine.
EOM
show() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage showvminfo "${id}"
}

# ----------------------------------------------------------------------- start

desc "start" <<EOM
Usage:
  $_ME start (<name> | <uuid>) [--headless]

Description:
  Start the VM with the given name or UUID.
EOM
start() {
  local headless=
  local id=

  for arg in "${_COMMAND_ARGV[@]:-}"
  do
    case "${arg}" in
      --headless) headless=1;;
      *) id="${arg}";;
    esac
  done

  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi

  if [[ -n "${headless}" ]]
  then
    VBoxManage startvm "${id}" --type headless
  else
    VBoxManage startvm "${id}"
  fi
}

# ---------------------------------------------------------------------- status

desc "status" <<EOM
Usage:
  $_ME status [(<name> | <uuid>) [--long|-l]]

Options:
  -l --long  Display long-form status information for the specified VM.

Description:
  When no argument has been passed, this acts as an alias for
  \`$_ME list status\` and displays the status for all of the VMs. When
  passed a VM name or UUID, the status aka state of that VM is displayed.
EOM
status() {
  local id=
  local status_string=
  local long=0

  for arg in "${_COMMAND_ARGV[@]:1}"
  do
    case "${arg}" in
      -l|--long) long=1;;
      *) [[ -z "${id}" ]] && id="${arg}";;
    esac
  done

  if [[ -n "${id}" ]]
  then
    if ((long))
    then
      status_string="$(
        $_ME show "${id}" \
          | awk '/State:/ {for (i=2; i<NF; i++) printf $i " "; print $NF}'
      )"
    else
      # Only display state name. Using two `awk` statements since the state
      # can be displayed with one or more word, which is viewed as multiple
      # fields. Instead get all of the fields and then blank out everything
      # after the first parenthesis.
      status_string="$(
        $_ME show "${id}" \
          | awk '/State:/ {for (i=2; i<NF; i++) printf $i " "; print $NF}' \
          | awk '{gsub(/\(.*/,"");print}'
      )"
    fi
    _emojify_status "${status_string}"
  else
    $_ME list status
  fi
}

# ------------------------------------------------------------------------ stop

desc "stop" <<EOM
Usage:
  $_ME stop (<name> | <uuid>)

Description:
  Command: \`VBoxManage controlvm <vm> savestate\`

  Save the current state of the VM to disk and then stop the VM. (This is
  equivalent to selecting the "Close" item in the "Machine" menu of the GUI or
  pressing the window's close button, and then selecting "Save the machine
  state" in the dialog.)
EOM
stop() {
  local id="${1:-}"
  if [[ -z "${id}" ]]
  then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" savestate
}

###############################################################################
# _main
###############################################################################

_main
