#!/usr/bin/env bash
#########################################################################
# vbox - a bask script
#
# Add this script and bask to your $PATH. For usage information, run:
# vbox help
#########################################################################

source "$(which bask)"

desc kill <<EOM
Usage:
  $_ME kill <name|uuid>

Description:
  Command: \`VBoxManage controlvm <vm> poweroff\`

  Has the same effect on a virtual machine as pulling the power cable on a real
  computer. The state of the VM is not saved beforehand, and data may be lost.
  (This is equivalent to selecting the "Close" item in the "Machine" menu of
  the GUI or pressing the window's close button, and then selecting "Power off
  the machine" in the dialog.)
EOM
kill() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" poweroff
}

desc list <<EOM
Usage:
  $_ME list [running|status]

Arguments:
  running  List all running VMs.
  status   Display all VMs with basic status information.

Description:
  List VirtualBox VMs.
EOM
list() {
  if _contains "running" "${command_parameters[@]:-}"; then
    VBoxManage list runningvms
  elif _contains "status" "${command_parameters[@]:-}"; then
    VBoxManage list vms -l | \
      grep -e ^Name: -e ^State | \
      sed s/\ \ //g | \
      cut -d: -f2-
  else
    VBoxManage list vms
  fi
}

desc pause <<EOM
Usage:
  $_ME pause <name|uuid>

Description:
  Command: \`VBoxManage controlvm <vm> pause\`

  Temporarily puts a virtual machine on hold, without changing its state for
  good. The VM window will be painted in gray to indicate that the VM is
  currently paused. (This is equivalent to selecting the "Pause" item in the
  "Machine" menu of the GUI.)
EOM
pause() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" pause
}

desc reset <<EOM
Usage:
  $_ME reset <name|uuid>

Description:
  Command: \`VBoxManage controlvm <vm> reset\`

  Has the same effect on a virtual machine as pressing the "Reset" button on a
  real computer: a cold reboot of the virtual machine, which will restart and
  boot the guest operating system again immediately. The state of the VM is not
  saved beforehand, and data may be lost. (This is equivalent to selecting the
  "Reset" item in the "Machine" menu of the GUI.)
EOM
stop() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" poweroff
}

desc resume <<EOM
Usage:
  $_ME resume <name|uuid>

Description:
  Command: \`VBoxManage controlvm <vm> resume\`

  Undo a previous pause command. (This is equivalent to selecting the "Resume"
  item in the "Machine" menu of the GUI.)
EOM
resume() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" resume
}

desc show <<EOM
Usage:
  $_ME show <name|uuid>

Description:
  Command: \`VBoxManage showvminfo <vm>\`

  Show information about a particular virtual machine.
EOM
show() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage showvminfo "${id}"
}

desc start <<EOM
Usage:
  $_ME start <name|uuid> [--headless]

Description:
  Start the VM with the given name or UUID.
EOM
start() {
  local headless=
  local id=

  for arg in "${command_argv[@]:-}"; do
    case "${arg}" in
      --headless) headless=1;;
      *) id="${arg}";;
    esac
  done

  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi

  if [[ -n "${headless}" ]]; then
    VBoxManage startvm "${id}" --type headless
  else
    VBoxManage startvm "${id}"
  fi
}

desc stop <<EOM
Usage:
  $_ME stop <name|uuid>

Description:
  Command: \`VBoxManage controlvm <vm> savestate\`

  Save the current state of the VM to disk and then stop the VM. (This is
  equivalent to selecting the "Close" item in the "Machine" menu of the GUI or
  pressing the window's close button, and then selecting "Save the machine
  state" in the dialog.)
EOM
stop() {
  local id="${1:-}"
  if [[ -z "${id}" ]]; then
    _die printf "Name or UUID not provided.\n"
  fi
  VBoxManage controlvm "${id}" savestate
}

_init
